### ISSUE TITLE
Where to define header image 

### ISSUE THREAD

**Issue by stephanj** [voxxrin/voxxrin3#15]
VoxxedDays Luxembourg was able to define a different image for the logo and the header bg image

![image](https://github.com/voxxrin/voxxrin3/assets/179457/63c4052d-3eea-4ad2-826f-4f6c861c2c8e)
![image](https://github.com/voxxrin/voxxrin3/assets/179457/7367a7b5-1723-49c7-9de6-ba72f323c859)

How can this be achieved? 

The backgroundUrl in this example is never used...  thoughts?

![image](https://github.com/voxxrin/voxxrin3/assets/179457/ebcb0f66-53ee-4879-8527-8e3c7013290c)

**Comment by fcamblor** [comment]
Created #18 for a larger purpose help page

I think in your case, this is due to current devoxx crawling implementation which, first, look at [CFP's `eventImageURL` attribute](https://dvbe23.cfp.dev/api/public/event), then fallback on descriptor's `backgroundUrl` : 
https://github.com/voxxrin/voxxrin3/blob/develop/cloud/functions/src/crawlers/devoxx/crawler.ts#L78

I assume that I should either remove this `backgroundUrl` from descriptor OR stop relying on CFP's `eventImageURL` (or use this one for the `logoUrl` as it seems to be what you expect)

What are your thoughts ?

And FYI, `backgroundUrl` and `logoUrl` are used currently :
- `backgroundUrl` (black arrow) : on Event listing page's pinned items + on Event schedule's header
- `logoUrl` (red arrow) : on Event listing page's available and pinned items

<img width="300" alt="Voxxrin_-_Your_conference_companion" src="https://github.com/voxxrin/voxxrin3/assets/603815/649d9eb9-14be-4b32-bbfa-67a28b4cead9">
<img width="300" alt="Voxxrin_-_Your_conference_companion" src="https://github.com/voxxrin/voxxrin3/assets/603815/b69104a7-58af-406a-bec8-8789b32d0b5d">

**Comment by stephanj** [comment]
Yes, please stop relying on CFP's and use all images info in the json gist file.

**Comment by fcamblor** [comment]
fixed through 0903c1f58d7661f797d045ff8561c583c40ee3d6 (deployed on demo environment)
