### ISSUE TITLE
Add public recording link to talks

### ISSUE THREAD

**Issue by DimitriHautot** [voxxrin/voxxrin3#62]
On many conferences, especially the Devoxx galaxy's, talks are recorded and available soon after.

It would be nice to be able to put the recording link in the talk details afterwards, so that missed talks can be easily caught up.

I personally keep my favourites talks to more easily remind me them for later vision.

What do you think ?

**Comment by fcamblor** [comment]
Yes, this is totally aligned with my vision

We already have some features implemented going toward this direction (but it was a little too early to move them to Production for Devoxx BE) : 
- First, #19 : [the **watch later** feature](https://github.com/voxxrin/voxxrin3/wiki/Voxxrin-3-features-showcase#marking-a-talk-as-to-watch-later), allowing you to mark talks as "to watch later" (can be useful if, for a given timeslot, you have multiple favorites). Once PUSH notification will be implementation, we might even consider PUSHing notifications to attendees having "watch later" talks
<img width="384" alt="Cursor_and_Voxxrin_-_Your_conference_companion" src="https://github.com/voxxrin/voxxrin3/assets/603815/487dce3e-e159-40cb-bdab-ecb560b3f874">

- Then, you have the [Speakers should be able to provide web URLs for materials related to their talk](https://github.com/voxxrin/voxxrin3/wiki/Voxxrin-3-features-showcase#you-should-be-able-to-provide-asset-urls-to-your-talk) (recording, slides, transcript, source repository, etc.)

https://github.com/voxxrin/voxxrin3/assets/603815/3092ba9e-5750-4ade-84b5-fe04a9543456

I will close the issue, because I think it can be covered by all these stories :-)

**Comment by DimitriHautot** [comment]
Thanks Frédéric, these features indeed cover my request.

Great app by the way, let's hope it will be there for years. 🤩
(there has been so many attempt so far... 🙄)
